modLoader = "javafml"
loaderVersion = "[45,)"
license = "Assets: All Rights Reserved; Code: LGPL-3.0"
issueTrackerURL="https://github.com/The-Aether-Team/Nitrogen/issues"

[[mods]]
modId = "nitrogen_internals"
version = "${file.jarVersion}"
displayName = "Nitrogen"
displayURL = "https://github.com/The-Aether-Team/Nitrogen"
credits = "The Aether Team"
authors = "bconlon"
description = '''
    A library used for the Aether series of mods.'''

[[dependencies.nitrogen_internals]]
    modId = "forge"
    mandatory = true
    versionRange = "[45.1.0,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.nitrogen_internals]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.4]"
    ordering = "NONE"
    side = "BOTH"
